### ISSUE TITLE
Word/punctuation string modifiers complicates parsing syntax that is sensitive to newlines 

### ISSUE THREAD

**Issue by ntezak** [wdebeaum/PEG.jl#3]
This package is very neat. Thanks for releasing it!

For grammars that are sensitive to line breaks, the word and punctuation macro modifiers `r","p` or `r","w` cannot be used in some cases, necessitating (AFAIU) more complicated workarounds. It would be convenient to either have versions of `p` and `w` modifiers that do not match all whitespace, but just horizontal whitespace or to just make that the default behavior of `p` and `w`.

@wdebeaum: what are your thoughts? I would be very happy to submit a PR.

**Comment by wdebeaum** [comment]
Thanks for your interest in PEG.jl, and sorry for my delay in replying (I was on vacation, and then working through the backlog from that vacation).

I had thought about doing something like this, but I was kind of on the fence because I wanted to keep it simple. But I think seeing that someone else wants this feature too has pushed me off the fence.

I think it might be good to have one extra modifier that changes the behavior of `p` and `w`, rather than two modifiers that copy `p` and `w` with the change. Modifier letters are a scarce resource, and in addition to overriding Julia's `imsx`, I'd like to avoid redefining those that are in active use in other languages like Perl. That leaves `bfhjkqtvyz`. How about `h` for horizontal?

I think most whitespace characters are horizontal, so I should just list the ones that aren't, in a negative lookahead before the `\s`. That would turn the implementation of `p` from `\s*` to `(?:(?![\r\n\v\f\u85])\s)*`. That is to say, the vertical whitespace characters are: carriage return, line feed, vertical tab, form feed, and [next line](http://www.fileformat.info/info/unicode/char/85/index.htm). Did I miss any?

**Comment by ntezak** [comment]
Thanks for your reply! There is actually a special horizontal whitespace `\h` regex form, so we can probably use that directly, right?

**Comment by ntezak** [comment]
So would this then be?

1. `r","p` to match comma, followed by any whitespace
2. `r","ph` to match comma, followed by any horizontal whitespace
3. `r"BEGIN"w` to match "BEGIN", followed by any whitespace
4. `r"BEGIN"wh` to match "BEGIN", followed by any horizontal whitespace

**Comment by wdebeaum** [comment]
Oh, `\h` is good to know! Apparently it was added in Perl 5.10, after I learned Perl 5.6 :)

And yes, your four examples are correct.

OK, I just committed this change; eventually this will be version 0.2.0, once the CI tests finish and I submit the version tag/metadata.

**Comment by wdebeaum** [comment]
Hm, mac tests are taking forever to even start running. Submitted it anyway; hopefully it'll get there eventually.

**Comment by ntezak** [comment]
They seem to have passed eventually. Thanks @wdebeaum, this is super helpful!
